# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: kaui
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

